apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: reactjs
  name: reactjs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reactjs
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-deploy.yml
        kompose.version: 1.37.0 (HEAD)
      labels:
        io.kompose.service: reactjs
    spec:
      containers:
        - image: nginx:latest
          name: reactjs
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "500Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          # Add readiness and liveness probes
          readinessProbe:
            httpGet:
              path: /
              port: 80
      restartPolicy: Always
