apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-deploy.yml
    kompose.version: 1.37.0 (HEAD)
  labels:
    io.kompose.service: reactjs
  name: reactjs
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 80
  selector:
    io.kompose.service: reactjs
